# Generated by Django 2.0 on 2021-06-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('rate_nums', models.IntegerField()),
                ('intro', models.CharField(max_length=1500)),
                ('tags', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('ccontent', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('bid', models.ManyToManyField(to='aibook_Model.Books')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='uid',
            field=models.ManyToManyField(to='aibook_Model.Users'),
        ),
    ]
