# Generated by Django 2.0 on 2021-06-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibook_Model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='intro',
            field=models.CharField(max_length=2000),
        ),
    ]
