# Generated by Django 2.0 on 2021-06-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aibook_Model', '0002_auto_20210623_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='bid',
        ),
        migrations.AddField(
            model_name='comments',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aibook_Model.Books'),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='uid',
        ),
        migrations.AddField(
            model_name='comments',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aibook_Model.Users'),
        ),
    ]
