# Generated by Django 2.0 on 2021-06-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aibook_Model', '0003_auto_20210623_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
