# Generated by Django 2.0 on 2021-06-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aibook_Model', '0004_auto_20210623_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('ccontent', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aibook_Model.Books')),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aibook_Model.Users')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
